In [9]:
import numpy as np

In [11]:
a=np.array([1.2,2.5,3.2,1.8])

In [13]:
print(type(a))

<class 'numpy.ndarray'>


In [15]:
print(a.dtype)

float64


In [17]:
print(a.ndim)

1


In [19]:
print(a.shape)

(4,)


In [21]:
print(a.size)

4


In [23]:
a=np.array([1,2,4])

In [25]:
print(a.dtype)

int32


In [29]:
a=np.array([1,2,4],dtype=float)

In [31]:
print(a.dtype)

float64


In [33]:
print(a)

[1. 2. 4.]


In [35]:
b=np.array([True,False,True,True], dtype=bool)

In [37]:
print(b)

[ True False  True  True]


In [39]:
a=np.array([{"Toto":(45,2000)},{"Tata":(34,1500)}])

In [41]:
print(a.dtype)

object


In [43]:
a=np.arange(start=0,stop=10)

In [45]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [47]:
a=np.arange(start=0,stop=10,step=2)

In [49]:
print(a)

[0 2 4 6 8]


In [51]:
a=np.ones(shape=5)

In [53]:
print(a)

[1. 1. 1. 1. 1.]


In [55]:
a=np.full(shape=5,fill_value=3.2)

In [57]:
print(a)

[3.2 3.2 3.2 3.2 3.2]


In [59]:
a=np.loadtxt("vecteur.txt",dtype=float)

In [61]:
print(a)

[ 4.  5.  8. 16. 68. 14. 35.]


In [63]:
lst=[1.2,3.1,4.5]

In [65]:
print(type(lst))

<class 'list'>


In [67]:
a=np.asarray(lst,dtype=float)

In [69]:
print(type(a))

<class 'numpy.ndarray'>


In [71]:
print(a)

[1.2 3.1 4.5]


In [73]:
a=np.array([1.2,2.5,3.2,1.8])

In [75]:
a=np.append(a,10)

In [77]:
print(a)

[ 1.2  2.5  3.2  1.8 10. ]
